### ISSUE TITLE
"which: no javac in (/sbin:/bin:/usr/sbin:/usr/bin)" appears in puppet output during apply

### ISSUE THREAD

**Issue by pickgr** [maestrodev/puppet-maven#39]
Hello,

We are using a relatively new version of this module

commit 802b279c9d3542e15a04d06e671c72488fb75d5b

When we run the puppet apply we see the following

.
.
.
Info: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
which: no javac in (/sbin:/bin:/usr/sbin:/usr/bin)
Info: Caching catalog for XXXXXX.XXX.XX
Info: Applying configuration version '1414012210'
Notice: Finished catalog run in 5.48 seconds

Can the "which: no javac in (/sbin:/bin:/usr/sbin:/usr/bin)" be supressed?

I wasn't able to track down where this is coming from in the code.

thanks,
Garret

**Comment by TimMcgrawww** [comment]
I got this error too, how garrt u fixed this error?
