### ISSUE TITLE
Documentation for setting the 'profiles' element via maven::settings class

### ISSUE THREAD

**Issue by craigbarrau** [maestrodev/puppet-maven#47]
Would it be possible to get an example of setting profiles in maven::settings class?

I am trying to add the following to settings.xml

    <profile>
      <repositories>
        <repository>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
          <id>central</id>
          <name>libs-release</name>
          <url>http://artifactory.mycompany/artifactory/libs-release</url>
        </repository>
        <repository>
          <snapshots />
          <id>snapshots</id>
          <name>libs-snapshot</name>
          <url>http://artifactory.mycompany/artifactory/libs-snapshot</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
          <id>central</id>
          <name>plugins-release</name>
          <url>http://artifactory.mycompany/artifactory/plugins-release</url>
        </pluginRepository>
        <pluginRepository>
          <snapshots />
          <id>snapshots</id>
          <name>plugins-snapshot</name>
          <url>http://artifactory.mycompany/artifactory/plugins-snapshot</url>
        </pluginRepository>
      </pluginRepositories>
      <id>artifactory</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
    </profile>
 
Thanks!

**Comment by carlossg** [comment]
there's no direct support for profiles, you set the `repos` param, see https://github.com/maestrodev/puppet-maven/blob/master/templates/settings.xml.erb

**Comment by craigbarrau** [comment]
Thanks for the response. I don't think I need to use profiles to be able to model the same functionality as in the xml above. However, there are different urls for repositories and pluginRepositories. Looking into the settings.xml.erb it looks as if it sets the repos for both repositories and pluginRepositories and there is no way to distinguish the types of repository and generate the xml correctly based on this.

Below is the best I could come up with
```
maven::settings { 'maven':
    repos => [
	    {
		      id       => "libs-release",
		      url      => "http://artifactory.mycompany/artifactory/libs-release",
		      name     => "central",
		      snapshots => {  enabled => 'false', }
      }, {
          id       => "libs-snapshot",
          url      => "http://artifactory.mycompany/artifactory/libs-snapshot",
          name     => "snapshots",
      },
      {
          id       => "plugins-release",
          url      => "http://artifactory.mycompany/artifactory/plugins-release",
          name     => "plugins-release",
          snapshots => { enabled => 'false', }
      }, {
          id       => "plugins-snapshot",
          url      => "http://artifactory.mycompany/artifactory/plugins-snapshot",
          name     => "plugins-snapshots",
      }      
    ],
  }
```

but the settings.xml that is output is this. Notice the repositories and pluginRepositories are set the same.
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

  <profiles>
    <profile>
      <id>default-repo</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>libs-release</id>
          <name>central</name>
          <url>http://artifactory.mycompany/artifactory/libs-release</url>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </repository>
        <repository>
          <id>libs-snapshot</id>
          <name>snapshots</name>
          <url>http://artifactory.mycompany/artifactory/libs-snapshot</url>
        </repository>
        <repository>
          <id>plugins-release</id>
          <name>plugins-release</name>
          <url>http://artifactory.mycompany/artifactory/plugins-release</url>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </repository>
        <repository>
          <id>plugins-snapshot</id>
          <name>plugins-snapshots</name>
          <url>http://artifactory.mycompany/artifactory/plugins-snapshot</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>libs-release</id>
          <name>central</name>
          <url>http://artifactory.mycompany/artifactory/libs-release</url>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </pluginRepository>
        <pluginRepository>
          <id>libs-snapshot</id>
          <name>snapshots</name>
          <url>http://artifactory.mycompany/artifactory/libs-snapshot</url>
        </pluginRepository>
        <pluginRepository>
          <id>plugins-release</id>
          <name>plugins-release</name>
          <url>http://artifactory.mycompany/artifactory/plugins-release</url>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </pluginRepository>
        <pluginRepository>
          <id>plugins-snapshot</id>
          <name>plugins-snapshots</name>
          <url>http://artifactory.mycompany/artifactory/plugins-snapshot</url>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>

</settings>
```

Any change of creating a new plugin_repos parameter?

**Comment by carlossg** [comment]
PRs welcome
